### PR TITLE
2.5 fixes

### PR DESCRIPTION
**Pull request by g-bougard**
This patches fix the HTTP Server integration:
 - copy the right default configurations
 - use the right default folder where to look for plugins configurations

### CODE REVIEW

**Comment by g-bougard** [comment]
First commit can be omitted as it is just a patch sanitize.

**Review by trasher — CHANGES_REQUESTED** [review]
You have to fill the changelog entry on both specfiles

**Comment by trasher** [comment]
BTW, for the next time, please prefer to open PR against the official Fedora package at: https://src.fedoraproject.org/rpms/fusioninventory-agent

Thank you

**Comment by trasher** [comment]
For the first commit, I just took the upstream commit as is; if you drop part of the patch, this no longer match upstream commit checksum; so please drop it.

**Review by trasher — APPROVED** [review]

**Pull request merged**
